### ISSUE TITLE
Security Data Issues Secrets in clear text

### ISSUE THREAD

**Issue by shaybenb** [mehdiamenein/docker-collections#1]
Hi,<br><br>url : https://github.com/mehdiamenein/docker-collections/blob/ae0c4d914c79b477a54954a2a2841072534b29e3/vuejs-laravel-mysql/docker-compose.yml <br><br>You have commit that need to remove from the github history<br>attacker can see it and use it ...<br><br>encrypt your secrets !!!!<br><br>Our Bug Help you to be more Secure and protect your data ?<br>Buy me a coffee (or more likely a beer)<br>https://www.paypal.com/paypalme/bugbounty1/150USD<br>https://www.buymeacoffee.com/bugbounty<br>☕☕☕☕☕

**Comment by mehdiamenein** [comment]
Hi, thank you for the note, I will make a new commit and will change it

Although it will remain in the history however that is not real data anymore, all those resources are removed before I even add them to this repo + these were docker composes & dockerfiles I had on my computer which I usually use as starting points and tweak them per project

in case of a secure secret I usually use either docker secret or kubernete secret APIs + usually we define environment values in .env files which are part of our .gitignore and will later add to the environment of our machine

in case of anyone going to see this issue and not having a security guideline or is not familiar with secrets in context of docker or kubernetes, then feel free to contact the @shaybenb

**Comment by shaybenb** [comment]
Our Bug Help you to be more Secure and protect your data ?
Buy me a coffee (or more likely a beer)
https://www.paypal.com/paypalme/bugbounty1/150USD
https://www.buymeacoffee.com/bugbounty
☕☕☕☕☕
